name: Exploring Variables and Secrets

on: 
    workflow_dispatch:

env:
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: build
              run: docker build -t ${{ vars.CONTAINER_REGISTERY }}/"${{ vars.DOCKER_USERNAME }}"/$IMAGE_NAME:MostafaKassab .

            - name: login
              run: echo ${{ secrets.DOCKER_PASS }} | docker login ${{ vars.CONTAINER_REGISTERY }} -u ${{ vars.DOCKER_USERNAME }} --password-stdin

            - name: push
              run: docker push ${{ vars.CONTAINER_REGISTERY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:MostafaKassab