name: workflow 1
on: push


jobs:
    Task1:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome 
              run: |
                echo "Hello world"
                sudo apt update -y
                sudo apt install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                cat dragon.txt

    Task2:
        runs-on: ubuntu-latest
        steps:
            - name: Show readme 
              run: |
                echo "Contents of README.md:"
                cat README.md
                echo ""
                
