name: workflow 1
on: push


jobs:
    Task1:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome 
              run: |
                echo "Hello world"
                sleep 15

    Task2:
        runs-on: ubuntu-latest
        steps:
            - name: checkout 
              uses: actions/checkout@v4

            - name: Read README file
              run: |
                echo "Contents of README.md:"
                cat README.md

            - name: script
              run: |
                ls -ltra
                chmod +x .githunb/workflows/script.sh
                sh .github/workflows/script.sh

                
